---
title: "Data Science I HW 6"
author: "Hingling Yu"
date: "2023-11-29"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(patchwork)
library(rnoaa)
library(dplyr)
library(modelr)
library(purrr)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

```


## Problem 2
### Fetching and preparing weather data
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())

```

### Create bootstrap function 

```{r}
set.seed(2)
sample_bootstrap = 
  function(data_frame) {
    data_frame %>% sample_frac(replace = TRUE)
  }

```

### Create 5000 bootstrap samples

```{r}
bootstrap_data = 
  weather_df %>%  
  modelr::bootstrap(n = 5000) %>% 
  mutate(
    lm_models = map(strap, ~lm(tmax ~ tmin + prcp, data = .)),
    beta_glance = map(lm_models, broom::glance),
    beta_tidy = map(lm_models, broom::tidy)) %>% 
  unnest(beta_glance, beta_tidy) %>% 
  select(.id, term, estimate, r.squared) %>% 
  pivot_wider(
    names_from = term, 
    values_from = estimate
  ) %>% 
  rename(
    beta_0 = `(Intercept)`,
    beta_1 = tmin,
    beta_2 = prcp
  )
```

### Confidence interval for $\hat{r}^2$

```{r}
r_squared_ci = 
  bootstrap_data %>%
  select(r.squared) %>%
  summarize(
    ci_lower = quantile(r.squared, 0.025),
    ci_upper = quantile(r.squared, 0.975)
  )

r_squared_ci
```
### Plotting distribution of $\hat{r}^2$

```{r}
bootstrap_data %>%
  select(r.squared) %>%
  ggplot(aes(x = r.squared)) + 
  geom_density(fill = "pink", color = "black") + 
  labs(
    title = "Density of R-Squared Bootstrap Estimates",
    x = "R-squared Estimate",
    y = "Density"
  )
```


